# Generated by Django 4.2.11 on 2026-03-28 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='alertrecipient',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='emergencypanic',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='alert',
            name='external_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('crowd', 'Crowd Alert'), ('emergency', 'Emergency'), ('security', 'Security Alert'), ('weather', 'Weather Alert'), ('natural_disaster', 'Natural Disaster'), ('news', 'Breaking News'), ('system', 'System Alert')], default='security', max_length=20),
        ),
        migrations.AlterField(
            model_name='alert',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('emergency', 'Emergency')], default='medium', max_length=10),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['source', 'external_id'], name='alerts_aler_source_a41d57_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['priority', 'created_at'], name='alerts_aler_priorit_15bbf3_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['alert_type', 'is_active'], name='alerts_aler_alert_t_3344e6_idx'),
        ),
    ]
