# Generated by Django 4.2.11 on 2026-03-29 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incident',
            options={'ordering': ['-reported_at']},
        ),
        migrations.AlterModelOptions(
            name='incidentcomment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_type',
            field=models.CharField(choices=[('accident', 'Accident'), ('medical', 'Medical Emergency'), ('security', 'Security Issue'), ('crowd', 'Crowd Management'), ('fire', 'Fire'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='incident',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
