# Generated by Django 4.2.11 on 2026-03-29 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('incidents', '0002_alter_incident_options_alter_incidentcomment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='confidence_score',
            field=models.IntegerField(default=0, help_text='0-100 confidence score'),
        ),
        migrations.AddField(
            model_name='incident',
            name='fraud_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='is_fraud',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incident',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incident',
            name='validation_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='validation_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('verified', 'Verified - Real Report'), ('rejected', 'Rejected - False Report'), ('under_review', 'Under Review')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('rejected', 'Rejected - False Report')], default='pending', max_length=20),
        ),
    ]
